### ISSUE TITLE
Cast Web Service Manager --need help

### ISSUE THREAD

**Issue by IAmTron** [vervallsweg/cast-web-api#104]
Sorry new to Git so i apologize if this is not the correct place but i ran into an issue with the Cast Web Service Manager ...please see below.

Groovy.lang.MissingMethodException: No signature of method: script_dth_metadata_8aaf2c7d_ca42_4962_ae71_9c8dd2cea960.appSetting() is applicable for argument types: (java.lang.String) values: [api] Possible solutions: typeSetting(java.lang.String), typeSetting(java.util.Map), typeSetting(java.lang.String, java.lang.String), getSettings(), setSettings(java.lang.Object), typeSetting(java.lang.String, java.lang.String, java.util.List)

**Comment by vervallsweg** [comment]
https://github.com/vervallsweg/smartthings/issues/54

Seems to be the same. Will use this, since it seems smartthings, not api related.
