### ISSUE TITLE
TypeError: Cannot read property 'playerState' of undefined

### ISSUE THREAD

**Issue by mortesan** [vervallsweg/cast-web-api#24]
When I'm trying to use the /setMediaPlayback i get error 500 and on the server I get Exception caught: TypeError: Cannot read property 'playerState' of undefined.
I can hear my chromecast trying to connect and can see the stream image for a second before it seems to disconnect from the chromecast device (chromecast audio)

**Comment by vervallsweg** [comment]
Just guessing that it's a media error. Can you provide the parameters you used and maybe some logs?

**Comment by mortesan** [comment]
Here is the parameters I used:
http://IP:PORT/setMediaPlayback?address=CHROMECASTIP&mediaType=mp3&mediaUrl=http://lyd.nrk.no/nrk_radio_p3_mp3_m&mediaStreamType=LIVE&mediaTitle=NRK&mediaSubtitle=P3&mediaImageUrl=https://lh5.ggpht.com/wZsGOrwpMuOa4SDGQ5N1oH1TV-ZAh7t4c0kUj7kugJqrsW5y5R5qlwPk3vjBm0K9ZaA=w300

**Comment by vervallsweg** [comment]
Ok, it's a parameter error. The mediaStreamType parameter requires the Google Cast ["media type string" ](https://developers.google.com/cast/docs/media#media-type-strings), for mp3 that would be audio/mp3:

`http://IP:PORT/setMediaPlayback?address=CHROMECASTIP&mediaType=audio/mp3&mediaUrl=http://lyd.nrk.no/nrk_radio_p3_mp3_m&mediaStreamType=LIVE&mediaTitle=NRK&mediaSubtitle=P3&mediaImageUrl=https://lh5.ggpht.com/wZsGOrwpMuOa4SDGQ5N1oH1TV-ZAh7t4c0kUj7kugJqrsW5y5R5qlwPk3vjBm0K9ZaA=w300`

I'll clarify the documentation soon accordingly. Feel free to reopen if the issue persists :)
