### ISSUE TITLE
deviceFriendlyName missing for one device

### ISSUE THREAD

**Issue by janwerner** [vervallsweg/cast-web-api#48]
Using the latest version from Github (cast-web-api version 0.2.2), Google Home, Google Home Mini, NVIDIA Shield and a Cast Group all show up correctly, while my Sony Soundbar HT-NT5 shows up but doesn't have a `deviceFriendlyName`

**Comment by vervallsweg** [comment]
Can you maybe run http://{apiAddress}/getDevices a couple of times in a row and see whether it only sometimes has a friendly name?
If it still doesn't show up maybe increase the discoveryTimeout and run the above commands again?

I'm sorry, but I only have Google Devices and was always wondering whether the OEM implementation somehow differs from Google's.

**Comment by vervallsweg** [comment]
Oh and just realized discoveryTimeout is not documented, will do that ASAP. For the meantime, it should work like every other adjustable parameter.

**Comment by janwerner** [comment]
Hi, tried this a couple of times and also with a discoveryTimeout value of 10 seconds - result is the same: Sony Soundbar is missing its friendlyName, so I guess you're right, OEM implementation is probably different somehow. I did a tcpdump - not sure if that helps.

This is the `deviceFriendlyName` for the HT-NT5:

![image](https://user-images.githubusercontent.com/1213706/33598617-b7f2f9f4-d9a3-11e7-9c12-97af4a581d1e.png)

Here's the dump: [tcpdump.zip](https://github.com/vervallsweg/cast-web-api/files/1530384/tcpdump.zip)

**Comment by jg123** [comment]
My pull request should fix this: #56

**Comment by vervallsweg** [comment]
Fix for this by @jg123 will be released in v0.2.4 soon!
