### ISSUE TITLE
forever =  background process

### ISSUE THREAD

**Issue by Bboy486** [vervallsweg/cast-web-api#67]
Please clarify for me. If I run $ npm install forever -g that means I do not have to re-run the cast-web-api command when windows restarts right?

If not, do you know how I can turn the CMD into a batch where it changes directories, and then runs the cast-web-api. the following isnt working. 

@echo off

start cmd.exe 

cd C:\Users\Bboy\Desktop\cast-web-api-master\cast-web-api-master

cast-web-api

**Comment by vervallsweg** [comment]
Forever just keeps the script running as long as your computer is running. If you reboot, it won't restart that for you.

@echo off
cd C:\Users\Bboy\Desktop\cast-web-api-master\cast-web-api-master
forever start castWebApi.js

You can now also install the API [directly from npm](https://vervallsweg.github.io/smartthings/cast-web-installation-guide), without cloning the repo.

**Comment by Bboy486** [comment]
Is there a way to get this to start at start-up? My bat file above only brings up the c prompt in cmd

**Comment by vervallsweg** [comment]
Yes, safe the script I posted above as .bat and try it. If it starts the API successfully add the batch file to your auto start folder.
I'm not a windows user, but from what I remember theres a user auto start folder. Just symlink or copy the .bat file in there. As soon as you log in, the API will start.

**Comment by Bboy486** [comment]
![](https://i.imgur.com/rU3iYXc.jpg)![](https://i.imgur.com/qP4SXIU.jpg)

**Comment by vervallsweg** [comment]
Yeah, that looks successful to me. Can you access it on ip:3000? If so, just put it in auto start and you should be good!
