### ISSUE TITLE
google text to speech to Google hOME

### ISSUE THREAD

**Issue by pgibert** [vervallsweg/cast-web-api#71]
Hi,
 i succeded to  discover my GH and to modifiy volume  and pause/play with your cast-web -api  . That 's great ! Thanks
but i would like to text-to-speech with a simple curl command and it fails .... :-) . 
I tried ( follwing the doc) 
curl -H "Content-Type: application/json" -d '[{ {"mediaTitle":"my text","mediaSubtitle": "mytitle "}]' **http://{myIPaddress}/device/{MyGHid}/playMedia/** 
but i go error back : **error {}**
it seems i need to also set googleTTS':'language-code  in the JSON array?
Some example please , is it possible ? it would be very helpful
BR
phil

**Comment by vervallsweg** [comment]
`curl -H "Content-Type: application/json" -d '[{"mediaTitle":"My TTS text","mediaSubtitle": "My application title", "googleTTS":"en-US", "mediaImageUrl": "https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png"}]' http://{ip}/device/{id}/playMedia/`

1. JSON formatting error
2. googleTTS option missing
3. mediaImageUrl missing

**Comment by pgibert** [comment]
v
