### ISSUE TITLE
TTS Using Curl

### ISSUE THREAD

**Issue by adamrhoades** [vervallsweg/cast-web-api#76]
Hi there,

I've already got the api set up and working with smartthings, but would like to use a bash script on my home server to trigger some TTS alerts without involving smartthings, could anyone give me an example hello world script I can make use of please?

I've tried, but am struggling with the documentation.

Thanks in advance!

Adam

**Comment by vervallsweg** [comment]
Hi Adam,

this closed #71 issue should provide you with a curl example for TTS. Feel free to replace the message, subtitle and image to your liking.
If you need more info on how to use the API as a whole, I can link you to the swagger I just setup in beta.

Tobias
