### ISSUE TITLE
IP Address of localhost or 127.0.0.1 produces error

### ISSUE THREAD

**Issue by jmorris644** [vervallsweg/cast-web-api#78]
If I try to use localhost or 127.0.0.1 i get a

 "Error: getaddrinfo ENOTFOUND localhost locahost:3000 : http://localhost:3000/device"
statusCode: "ENOTFOUND"

if I use the actual IP address it works just fine.

**Comment by vervallsweg** [comment]
How do you 'use localhost or 127.0.0.1'? 
By accessing it through the browser or specifying it as hostname on startup of cast-web-api?

To make the api listen on localhost use `cast-web-api --hostname=127.0.0.1` . Then you can access it through localhost.

**Comment by jmorris644** [comment]
Thanks. That was what I was missing.
