### ISSUE TITLE
"Broadcast from...." Message, is it configurable?

### ISSUE THREAD

**Issue by ryancasler** [vervallsweg/cast-web-api#82]
Just wondered, as everyone probably is, if the Broadcast from message at the begin of broadcasts now is configurable or not?  Also, how would I remove my existing Google authorization so that I can use a different account?  I tried just inputting another one but it didn't seem to work.  it "took" but it still broadcast with the name of the old account.

**Comment by vervallsweg** [comment]
Go to your install directory of cast-web-api/assistant and remove client_secret.json, tokens.json.
Now you should be able to re auth from the web interface.

Can you maybe elaborate the Broadcast from question? I must admit I haven't looked into new assistant stuff for quite some time.

**Comment by ryancasler** [comment]
When you broadcast something, rather than just playing the broadcast is starts off by saying "Broadcast from (username)...." then does the boradcast.  it's the most annoying thing ever.  I really wish I'd invested in  Echos instead of GH's.  This really sucks ass.

**Comment by vervallsweg** [comment]
Yeah I see what you mean now. You probably already noticed that I was inactive for quite some time and haven't even used the assistant for months.
Yesterday I started rewriting the whole api and tested broadcast. I'll look into how we can use these new features. Expect a commit in the epxress branch soon.

Haha, look I'm not affiliated with Google in any way shape or form. We all do our stuff here at the goodwill and grace of Google. If they decide one day to do something in a particular way, that's how it's going to be from now on.

**Comment by ryancasler** [comment]
Oh, I completely understand.  My frustration is with google, not you.  You've been nothing short of amazing doing all this for us.
