### ISSUE TITLE
media.forEach is not a Function

### ISSUE THREAD

**Issue by sjlamine** [vervallsweg/cast-web-api#89]
Line 873, Media is an Object and you are doing a ForEach function on it.  ForEach can only be done on Arrays based on what I am reading.  

Your code is awesome and thanks for all of the good work

**Comment by sjlamine** [comment]
Got it working through SmartThings, as I expected... my problem

**Comment by vervallsweg** [comment]
Yes I assume the media you were trying to play wasn't an array. Just put it in [] usually works, more info is in the docs or in #71 (just remove the google tts things).
