### ISSUE TITLE
Music does not resume

### ISSUE THREAD

**Issue by a8ree** [vervallsweg/cast-web-api#91]
When using webcore to speak, the resume function does not work so music that was playing before speaking is stopped

**Comment by vervallsweg** [comment]
Yes. This is a google cast protocol limitation. It isn't possible to resume music or interact with the queue in any way, unless you use presets. You can only use play text and resume if the content playing [before was a preset.](https://vervallsweg.github.io/cast-web/What-can-I-play-through-presets/).

Alternatively there is a beta version of 1.1.0 where you can use the google assistant for playing voice messages. This doesn't stop your music playing. It's equivalent to the broadcast feature of your google homes.
