### ISSUE TITLE
Will this allow me to create a Google home alarm to play a private audio stream

### ISSUE THREAD

**Issue by mantistob** [vervallsweg/cast-web-api#96]
I have a shoutcast station permanently broadcasting an audio stream.  I have a Panasonic Allplay device that currently uses this as a morning alarm.  I want to switch to a Google home speaker and have the audio stream as a wake up alarm.

I was sent here suggesting this project may help.  Before I jump in, I am asking, am I on the right track?

**Comment by jager181** [comment]
Yes you would be able to do it. The shoutcast will ask you where to play the sound, and you would just choose the chromecast audio speaker at that point.

**Comment by vervallsweg** [comment]
Yes this should work. Reopen if you have further questions.
